### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by maxacademind2** [maxacademind1/github-crash-course#1]
I think it looks better if the main title is a bit more orange.

The styling rule could be changed like this:

```css
h1 {
  color: #efa82e;
}
```
